Augmented attributes interface-ref, payload-type and metric fields to mpls-static lsp
openconfig/public pull request #1021
Opened 2023-12-18 07:26 UTC by Shashank-arista

* (M) release/models/mpls/openconfig-mpls-static.yang
* (M) release/models/mpls/openconfig-mpls-types.yang
* (M) release/models/mpls/openconfig-mpls.yang

### Change Scope

* Augmented below attributes interface-ref, payload-type and metric in the path /network-instances/network-instance/mpls/lsps/static-lsps/static-lsp

  +--rw network-instances
     +--rw network-instance* [name]
        +--rw mpls
           +--rw lsps
              +--rw static-lsps
                 +--rw static-lsp* [name]
                    +--rw ingress
                    |  +--rw config
                    |  |  +--rw interface?        -> /oc-if:interfaces/interface/name
                    |  |  +--rw subinterface?     -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
                    |  |  +--rw payload-type?     identityref
                    |  |  +--rw metric?           uint8
                    |  +--ro state
                    |     +--ro interface?        -> /oc-if:interfaces/interface/name
                    |     +--ro subinterface?     -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
                    |     +--ro payload-type?     identityref
                    |     +--ro metric?           uint8
                    +--rw transit
                    |  +--rw config
                    |  |  +--rw interface?        -> /oc-if:interfaces/interface/name
                    |  |  +--rw subinterface?     -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
                    |  |  +--rw payload-type?     identityref
                    |  |  +--rw metric?           uint8
                    |  +--ro state
                    |     +--ro interface?        -> /oc-if:interfaces/interface/name
                    |     +--ro subinterface?     -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
                    |     +--ro payload-type?     identityref
                    |     +--ro metric?           uint8
                    +--rw egress
                       +--rw config
                       |  +--rw interface?        -> /oc-if:interfaces/interface/name
                       |  +--rw subinterface?     -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
                       |  +--rw payload-type?     identityref
                       |  +--rw metric?           uint8
                       +--ro state
                          +--ro interface?        -> /oc-if:interfaces/interface/name
                          +--ro subinterface?     -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
                          +--ro payload-type?     identityref
                          +--ro metric?           uint8

### Platform Implementations

 * Arista: https://www.arista.com/en/um-eos/eos-mpls-commands#xx1141474
 CLI configuration: mpls static top-label top_tag[ bgp peer [peer IP]] [DEST_INTF] NEXTHOP_ADDR ACTION [PRIORITY]

2024-02-06 18:01 UTC, dplore requested changes
Please add some additional description where pointed out.  I will help with an additional implementation reference.

2024-02-15 05:05 UTC, Shashank-arista commented on release/models/mpls/openconfig-mpls-types.yang
> +      "payload type MPLS";
I have updated the description as "Underlying payload type of the MPLS packet". Please check.

2024-02-15 05:06 UTC, Shashank-arista commented on release/models/mpls/openconfig-mpls-static.yang
> +        "MPLS payload type";
I have updated the description as "Specifies underlying payload type as MPLS label i.e., represents stacked MPLS labels". Please check

2024-02-15 05:06 UTC, Shashank-arista commented on release/models/mpls/openconfig-mpls-static.yang
> +        "MPLS static lsp route metric";
Updated the description as "Specifies metric value used for the MPLS route". Please check

2024-03-19 16:45 UTC, dplore commented
@Shashank-arista ping for any comments, especially regarding payload type.

2024-03-22 20:51 UTC, dplore commented
/gcbrun

2024-03-27 16:41 UTC, Shashank-arista commented
> @Shashank-arista ping for any comments, especially regarding payload type.

Hi @dplore, Sorry for the delay in getting back on this. I tried to investigate more on payload-type requirement. Arista CLI needs a payload-type mandatorily, although today most of hardware platforms depend on auto-decide for inferring it. But still, there is a use case where payload-type would be necessary/used on a certain platform where we would need to skip applying egress ACLs for certain labels which relies on payload-type for the functionality.

[no] mpls static top-label <inlabel> <nhaddr> [ intf ] { { swap-label <outlabel> } | { pop [ payload-type { ipv4 | ipv6 } [ **access-list bypass** ] ]  } } [ metric <metricval> ]

So, it seems payload-type is something not a mandatory attribute but would still be required in certain specific scenario.

2024-04-03 18:41 UTC, wenovus commented
/gcbrun

2024-04-05 05:55 UTC, dplore commented
> > @Shashank-arista ping for any comments, especially regarding payload type.
> 
> Hi @dplore, Sorry for the delay in getting back on this. I tried to investigate more on payload-type requirement. Arista CLI needs a payload-type mandatorily, although today most of hardware platforms depend on auto-decide for inferring it. But still, there is a use case where payload-type would be necessary/used on a certain platform where we would need to skip applying egress ACLs for certain labels which relies on payload-type for the functionality.
> 
> [no] mpls static top-label [ intf ] { { swap-label } | { pop [ payload-type { ipv4 | ipv6 } [ **access-list bypass** ] ] } } [ metric ]
> 
> So, it seems payload-type is something not a mandatory attribute but would still be required in certain specific scenario.

Ok.  In this scenario since we haven't identified at least 2 vendors that support payload type, nor the intent to add a payload type, nor specific operational use cases I suggest the payload type be removed from the OC model.  It could added via an Arista specific yang augment.

2024-04-05 16:53 UTC, Shashank-arista commented
> > > @Shashank-arista ping for any comments, especially regarding payload type.
> > 
> > 
> > Hi @dplore, Sorry for the delay in getting back on this. I tried to investigate more on payload-type requirement. Arista CLI needs a payload-type mandatorily, although today most of hardware platforms depend on auto-decide for inferring it. But still, there is a use case where payload-type would be necessary/used on a certain platform where we would need to skip applying egress ACLs for certain labels which relies on payload-type for the functionality.
> > [no] mpls static top-label [ intf ] { { swap-label } | { pop [ payload-type { ipv4 | ipv6 } [ **access-list bypass** ] ] } } [ metric ]
> > So, it seems payload-type is something not a mandatory attribute but would still be required in certain specific scenario.
> 
> Ok. In this scenario since we haven't identified at least 2 vendors that support payload type, nor the intent to add a payload type, nor specific operational use cases I suggest the payload type be removed from the OC model. It could added via an Arista specific yang augment.

Sure, @dplore. I have updated the pull request by removing the payload type related changes from OC model. Please review, thanks.

2024-04-10 00:36 UTC, dplore commented
/gcbrun

2024-04-10 16:35 UTC, dplore approved these changes
This LGTM.    Last call for comments!  I plan to merge this on April 17th, 2024.

2024-04-17 16:57 UTC, merged