Add static GUE encapsulation
openconfig/public pull request #1234
Opened 2024-12-17 01:44 UTC by danameme

### Change Scope

* Create `next-hop-groups` and `next-hops` under network instance to mimic existing AFT tree. This will allow systems to configure these in a network instance.
* Add a new container that allows static route configuration to point to next-hop-group. This will allow system to add encapsulation headers to packets.

### Platform Implementations

* [Arista](https://www.arista.com/en/support/toi/eos-4-30-1f/17688-support-for-ip-over-udp-encapsulation-using-nexthop-groups) support for GUE encapsulation.

### Tree view

```diff
@@ -3427,40 +3427,150 @@
         |  |     +--ro state
         |  |     |  +--ro interface-id?                 oc-if:interface-id
         |  |     |  +--ro apply-forwarding-policy?      -> ../../../../policies/policy/config/policy-id
         |  |     |  +--ro apply-vrf-selection-policy?   -> ../../../../policies/policy/config/policy-id
         |  |     +--rw interface-ref
         |  |        +--rw config
         |  |        |  +--rw interface?      -> /oc-if:interfaces/interface/name
         |  |        |  +--rw subinterface?   -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
         |  |        +--ro state
         |  |           +--ro interface?      -> /oc-if:interfaces/interface/name
         |  |           +--ro subinterface?   -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
         |  +--rw path-selection-groups
         |     +--rw path-selection-group* [group-id]
         |        +--rw group-id    -> ../config/group-id
         |        +--rw config
         |        |  +--rw group-id?   string
         |        |  +--rw mpls-lsp*   -> ../../../../../mpls/lsps/constrained-path/tunnels/tunnel/config/name
         |        +--ro state
         |           +--ro group-id?   string
         |           +--ro mpls-lsp*   -> ../../../../../mpls/lsps/constrained-path/tunnels/tunnel/config/name
+        +--rw next-hop-groups
+        |  +--rw next-hop-group* [name]
+        |     +--rw name         -> ../config/name
+        |     +--rw config
+        |     |  +--rw name?            string
+        |     |  +--rw id?              uint64
+        |     |  +--rw programmed-id?   uint64
+        |     +--ro state
+        |     |  +--ro name?            string
+        |     |  +--ro id?              uint64
+        |     |  +--ro programmed-id?   uint64
+        |     +--rw next-hops
+        |        +--rw next-hop* [index]
+        |           +--rw index     -> ../config/index
+        |           +--rw config
+        |           |  +--rw index?    -> ../../../../../../next-hops/next-hop/config/index
+        |           |  +--rw weight?   uint64
+        |           +--ro state
+        |              +--ro index?    -> ../../../../../../next-hops/next-hop/config/index
+        |              +--ro weight?   uint64
+        +--rw next-hops
+        |  +--rw next-hop* [index]
+        |     +--rw index            -> ../config/index
+        |     +--rw config
+        |     |  +--rw index?              uint64
+        |     |  +--rw programmed-index?   uint64
+        |     +--ro state
+        |     |  +--ro index?              uint64
+        |     |  +--ro programmed-index?   uint64
+        |     +--rw encap-headers
+        |        +--rw encap-header* [index]
+        |           +--rw index     -> ../config/index
+        |           +--rw config
+        |           |  +--rw index?   uint8
+        |           |  +--rw type?    oc-aftt:encapsulation-header-type
+        |           +--ro state
+        |           |  +--ro index?   uint8
+        |           |  +--ro type?    oc-aftt:encapsulation-header-type
+        |           +--rw gre
+        |           |  +--rw config
+        |           |  |  +--rw src-ip?       oc-inet:ip-address
+        |           |  |  +--rw dst-ip?       oc-inet:ip-address
+        |           |  |  +--rw dst-prefix?   oc-inet:ip-prefix
+        |           |  |  +--rw ttl?          uint8
+        |           |  +--ro state
+        |           |     +--ro src-ip?       oc-inet:ip-address
+        |           |     +--ro dst-ip?       oc-inet:ip-address
+        |           |     +--ro dst-prefix?   oc-inet:ip-prefix
+        |           |     +--ro ttl?          uint8
+        |           +--rw ipv4
+        |           |  +--rw config
+        |           |  |  +--rw src-ip?       oc-inet:ip-address
+        |           |  |  +--rw dst-ip?       oc-inet:ip-address
+        |           |  |  +--rw dst-prefix?   oc-inet:ip-prefix
+        |           |  +--ro state
+        |           |     +--ro src-ip?       oc-inet:ip-address
+        |           |     +--ro dst-ip?       oc-inet:ip-address
+        |           |     +--ro dst-prefix?   oc-inet:ip-prefix
+        |           +--rw ipv6
+        |           |  +--rw config
+        |           |  |  +--rw src-ip?       oc-inet:ip-address
+        |           |  |  +--rw dst-ip?       oc-inet:ip-address
+        |           |  |  +--rw dst-prefix?   oc-inet:ip-prefix
+        |           |  +--ro state
+        |           |     +--ro src-ip?       oc-inet:ip-address
+        |           |     +--ro dst-ip?       oc-inet:ip-address
+        |           |     +--ro dst-prefix?   oc-inet:ip-prefix
+        |           +--rw mpls
+        |           |  +--rw config
+        |           |  |  +--rw traffic-class?   oc-mplst:mpls-tc
+        |           |  |  +--rw label?           oc-mplst:mpls-label
+        |           |  |  +--rw mpls-ttl?        uint8
+        |           |  +--ro state
+        |           |     +--ro traffic-class?   oc-mplst:mpls-tc
+        |           |     +--ro label?           oc-mplst:mpls-label
+        |           |     +--ro mpls-ttl?        uint8
+        |           +--rw udp-v4
+        |           |  +--rw config
+        |           |  |  +--rw src-ip?         oc-inet:ip-address
+        |           |  |  +--rw dst-ip?         oc-inet:ip-address
+        |           |  |  +--rw dst-prefix?     oc-inet:ip-prefix
+        |           |  |  +--rw dscp?           oc-inet:dscp
+        |           |  |  +--rw src-udp-port?   oc-inet:port-number
+        |           |  |  +--rw dst-udp-port?   oc-inet:port-number
+        |           |  |  +--rw ip-ttl?         uint8
+        |           |  +--ro state
+        |           |     +--ro src-ip?         oc-inet:ip-address
+        |           |     +--ro dst-ip?         oc-inet:ip-address
+        |           |     +--ro dst-prefix?     oc-inet:ip-prefix
+        |           |     +--ro dscp?           oc-inet:dscp
+        |           |     +--ro src-udp-port?   oc-inet:port-number
+        |           |     +--ro dst-udp-port?   oc-inet:port-number
+        |           |     +--ro ip-ttl?         uint8
+        |           +--rw udp-v6
+        |              +--rw config
+        |              |  +--rw src-ip?         oc-inet:ip-address
+        |              |  +--rw dst-ip?         oc-inet:ip-address
+        |              |  +--rw dst-prefix?     oc-inet:ip-prefix
+        |              |  +--rw dscp?           oc-inet:dscp
+        |              |  +--rw src-udp-port?   oc-inet:port-number
+        |              |  +--rw dst-udp-port?   oc-inet:port-number
+        |              |  +--rw ip-ttl?         uint8
+        |              +--rw state
+        |                 +--rw src-ip?         oc-inet:ip-address
+        |                 +--rw dst-ip?         oc-inet:ip-address
+        |                 +--rw dst-prefix?     oc-inet:ip-prefix
+        |                 +--rw dscp?           oc-inet:dscp
+        |                 +--rw src-udp-port?   oc-inet:port-number
+        |                 +--rw dst-udp-port?   oc-inet:port-number
+        |                 +--rw ip-ttl?         uint8
         +--ro afts
         |  +--ro ipv4-unicast
         |  |  +--ro ipv4-entry* [prefix]
         |  |     +--ro prefix    ->  [...]

2024-12-18 02:21 UTC, robshakir commented
Dan, thanks for the contribution!

I'm not sure that this should be modelled this way. A few concerns:

 * we now have a new `next-hop-groups` at the `/network-instances/network-instance` level, which doesn't really relate to any feature. This at least should be grouped under something (e.g., should it be under the static route protocol, or policy forwarding?)
 * we need to decide whether this static encapsulation can sit within `policy-forwarding` like GRE encapsulation does. today, we have `/network-instances/network-instance/policy-forwarding/policies/policy/rules/rule/action/encapsulate-gre` -- in this case, we created a new AFT-like construct to be able to do this. I think this should probably live within policy-forwarding as with the other encapsulation use cases.
 * if we're re-using the AFT definitions -- let's just re-use the groupings rather than create a whole new model that duplicates a bunch of the content.

Happy to discuss further.

2024-12-18 03:14 UTC, robshakir commented
I see the discussion in #1208 that covered the objection to this being in `policy-forwarding`. If the problem is that this does not allow matching on specific policies, then that's OK -- but let's find somewhere other than straight in `network-instances` for it to live.

If this is always going to be specified via a static route -- then I suggest that we have this configured under the static routing sections of the model. 

I'd like to understand what the plan is to make this consistent with GRE encapsulation.

2024-12-18 06:22 UTC, dplore commented
> I see the discussion in #1208 that covered the objection to this being in `policy-forwarding`. If the problem is that this does not allow matching on specific policies, then that's OK -- but let's find somewhere other than straight in `network-instances` for it to live.
> 
> If this is always going to be specified via a static route -- then I suggest that we have this configured under the static routing sections of the model.
> 
> I'd like to understand what the plan is to make this consistent with GRE encapsulation. (i.e., will we deprecate `encapsulate-gre`).
> 
> There's some history of how this is modelled here: https://drive.google.com/file/d/1GVzP6ZQFlvbZvdLSZnhYlwrL6AIaLJl-/view?usp=sharing

I actually recommended to Dan that we create next-hop-groups at this level.  I'm happy to entertain some other suggestion though?

The intended concept is these user defined next-hop-groups are the static equivalent of gRIBI programmed next-hop-groups.  User defined next-hop-groups (and their child next-hops) can be referenced by static-routes, policy-forwarding and generically anything that would set or reference (user defined) next-hop-groups.

WDYT?

2024-12-18 06:23 UTC, dplore commented
/gcbrun

2024-12-19 01:00 UTC, akvasu commented
Hi Darren/Dan - 

We have been working on a proposal from Cisco, and we defined the next-hop group and next-hops (encap header) containers under the local-routing module (static route) like Rob suggested above. In addition, we were trying to define a "template" for common fields like the source-ip, dscp, ttl which can be re-used in all the next hops. This was just to reduce the repetition of fields, which in some cases can hit resource constraints on the ASIC (for example, an ASIC might only support a limited number of Source IP's or only a global UDP destination port) unless the backend implementation forces some form of templatization. The connection-endpoint can be extended to act as a template for such common fields. 

Finally the local route prefix would just use the next-hop group similar to how it currently refers to the local-next-hop. 

Most ACL and Policy forwarding implementations already support a redirect to a nexthop IP, and the local-route prefix can be used easily in such flows. 

Let us know what you think? 

Thanks

2024-12-19 20:38 UTC, dplore commented
> Hi Darren/Dan -
> 
> We have been working on a proposal from Cisco, and we defined the next-hop group and next-hops (encap header) containers under the local-routing module (static route) like Rob suggested above. In addition, we were trying to define a "template" for common fields like the source-ip, dscp, ttl which can be re-used in all the next hops. This was just to reduce the repetition of fields, which in some cases can hit resource constraints on the ASIC (for example, an ASIC might only support a limited number of Source IP's or only a global UDP destination port) unless the backend implementation forces some form of templatization. The connection-endpoint can be extended to act as a template for such common fields.
> 
> Finally the local route prefix would just use the next-hop group similar to how it currently refers to the local-next-hop.
> 
> Most ACL and Policy forwarding implementations already support a redirect to a nexthop IP, and the local-route prefix can be used easily in such flows.
> 
> Let us know what you think?
> 
> Thanks

Thanks for the comment.  We're working to produce another revision.

I like to idea of some way to reduce the repetition of the fields for the encap-headers.  One idea that comes to mind is to place the fields on the next-hop-group and declare that all the next-hops in that group must use the fields.  Just thinking out loud.

2024-12-21 00:20 UTC, akvasu commented
> > Hi Darren/Dan -
> > We have been working on a proposal from Cisco, and we defined the next-hop group and next-hops (encap header) containers under the local-routing module (static route) like Rob suggested above. In addition, we were trying to define a "template" for common fields like the source-ip, dscp, ttl which can be re-used in all the next hops. This was just to reduce the repetition of fields, which in some cases can hit resource constraints on the ASIC (for example, an ASIC might only support a limited number of Source IP's or only a global UDP destination port) unless the backend implementation forces some form of templatization. The connection-endpoint can be extended to act as a template for such common fields.
> > Finally the local route prefix would just use the next-hop group similar to how it currently refers to the local-next-hop.
> > Most ACL and Policy forwarding implementations already support a redirect to a nexthop IP, and the local-route prefix can be used easily in such flows.
> > Let us know what you think?
> > Thanks
> 
> Thanks for the comment. We're working to produce another revision.
> 
> I like to idea of some way to reduce the repetition of the fields for the encap-headers. One idea that comes to mind is to place the fields on the next-hop-group and declare that all the next-hops in that group must use the fields. Just thinking out loud.

Hi Darren, 

Yes the next-hop container might be one place to hold on the common fields. We were considering the connection-point as it already does something similar for VxLAN - https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-network-instance.html#network-instances-network-instance-connection-points-connection-point-endpoints-endpoint-vxlan

We can discuss further. Let us know if you would like to review what we've been working on at Cisco for this usecase.

2025-01-08 21:53 UTC, dplore commented
Ok, so the proposal is to move the next-hop-group/next-hops into the [local-routing module](https://source.corp.google.com/piper///depot/google3/third_party/openconfig/public/release/models/local-routing/openconfig-local-routing.yang), perhaps rooted at

`/network-instances/network-instance/protocols/protocol/static-nhg/`

(following the pattern of local-aggregates, static-routes which are also part of local-routing)

And move the attributes (encap-headers) from the next-hop up to the next-hop-group.  ie:
`/network-instances/network-instance/protocols/protocol/static-nhgs/static-nhg/config/encap-headers`

Thoughts?

2025-01-09 17:40 UTC, nokia1adam commented
The addition of statically configured next-hop-groups to OC (in local-routing context) is a very good step (a very big +1 from us) but please don't limit it to containing next-hops that only do tunnel encapsulation (GUE or other). All types of next-hops used by static routes should be supported. It is an implementation-specific matter if some types of next-hops cannot be combined with other types in the same NHG.

I don't have a strong view on whether the NHGs should be limited to use by static routes or also include use by policy-forwarding.

If a statically configured NHG is bound to a static route prefix I assume it will not be valid to define individual next-hops for that static route -- in other words, the use of NHG should be mutually exclusive with the use of individual next-hops.

2025-01-29 21:15 UTC, akalluru1 commented
> Ok, so the proposal is to move the next-hop-group/next-hops into the [local-routing module](https://source.corp.google.com/piper///depot/google3/third_party/openconfig/public/release/models/local-routing/openconfig-local-routing.yang), perhaps rooted at
> 
> `/network-instances/network-instance/protocols/protocol/static-nhg/`
> 
> (following the pattern of local-aggregates, static-routes which are also part of local-routing)
> 
> And move the attributes (encap-headers) from the next-hop up to the next-hop-group. ie: `/network-instances/network-instance/protocols/protocol/static-nhgs/static-nhg/config/encap-headers`
> 
> Thoughts?

Copying the discussion from community meeting for posterity, should the encap-headers stay in the NH (and not NHG) to support multiple/ecmp style encaps?

2025-02-07 02:50 UTC, danameme commented
Updated the model with changes moved to the local-routing module. 

The encap headers are in NH i(instead of NHG)

2025-02-11 17:05 UTC, dplore commented
/gcbrun

2025-02-21 07:05 UTC, danameme commented
Discussed with Darren and updated PR by moving the next-hop-groups and next-hops to a new container under rooted at `/network-instances/network-instance/static` instead of under protocols/protocol.

So that, these can be used in policy-forwarding if needed and also given that next-hop-groups/next-hops are not protocols.

2025-02-21 20:00 UTC, dplore commented
/gcbrun

2025-03-06 01:26 UTC, dplore commented
/gcbrun

2025-03-06 01:42 UTC, dplore commented
Added additional implementation references to the PR description.

2025-03-06 01:43 UTC, dplore commented
@danameme Some errors to correct:

```
network-instance/openconfig-network-instance-static.yang (38): error:
RFC 8407: 4.14: statement "container" must have a "description" substatement

network-instance/openconfig-network-instance-static.yang (265): error:
element "index" is in a "state" container and should have config value false
```

2025-03-06 01:48 UTC, dplore commented
@danameme please add the following fields to the newly introduced next-hops so they can be used generically, not just for encap-headers;

```diff
        |  +--rw next-hops
        |     +--rw next-hop* [index]
        |        +--rw index            -> ../config/index
        |        +--rw config
        |        |  +--rw index?   uint64
+        |        |  +--rw next-hop	leaf	union
+        |        |  +--rw recurse	leaf	boolean
+        |        |  +--rw metric	leaf	uint32
+        |        |  +--rw preference   uint64

```

2025-03-06 17:19 UTC, shasingh27 commented
hi,
i have some doubts can you please help clarify

QUESTION 1::::::
if we give something like this:
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 config index 1
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 encap-headers encap-header 1 udp-v4 config dst-ip 1.1.1.1
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 2 config index 2
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 2 encap-headers encap-header 2 config index 2
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 2 encap-headers encap-header 2 udp-v4 config dst-ip 2.2.2.2

set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP_GROUP nhg1 static-next-hop-groups static-next-hop-group snhg1 next-hops next-hop 2 config  index 2
 
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol STATIC DEFAULT static-routes static next-hop-group config name snhg1

>>> then what is the point of defining index 1 and 2 in protocol NEXT_HOP nh1, if we explicitely have to mention the index in protocol NEXT_HOP_GROUP nhg1 ?
------------------------------------------------
QUESTION 2:::::
if we have a situation like this:
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh2 next-hops next-hop 1 config index 1
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh2 next-hops next-hop 1 encap-headers encap-header 1 udp-v4 config dst-ip 2.2.2.2

set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 config index 1
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 encap-headers encap-header 1 udp-v4 config dst-ip 1.1.1.1

here for both NEXT_HOP nh2 and NEXT_HOP nh1, we have index 1 defined.
how will we deal with this ?
are we mentioning somewhere that multiple instances for protocol NEXT_HOP is not allowed ?

thanks
shashank

2025-03-06 22:02 UTC, akvasu commented
Can we import the "State" containers into config as done in this PR? When we were working on an alternate proposal in the past within Cisco, we wanted to re-use the AFT definitions, but we didn't as they were only state. Reading back from state doesn't always translate well, as state might be a combination of different hardware objects based on how the ASIC's implement a feature. 

Coming to the content of the PR, I've been discussing the implementation of this model within Cisco and we came up with some concerns, that I'll try to explain here. 

Lets start with defining some Nexthops like this - 

```
set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 2 encap-headers encap-header 1 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6080 dscp af43 ip-ttl 250 

set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh2 next-hops next-hop 2 encap-headers encap-header 1 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6635 dscp af43 ip-ttl 250 

set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh3 next-hops next-hop 2 encap-headers encap-header 1 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6615 dscp af43 ip-ttl 250 

**set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh4 next-hops next-hop 2 encap-headers encap-header 1 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6080 dscp af45 ip-ttl 250** 

**set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh5 next-hops next-hop 2 encap-headers encap-header 1 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6080 dscp af43 ip-ttl 64** 
```

We have defined 5 nexthops, and they all have the same SRC and DST IP, and all are the same tunnel type udp-v4. Going by our past work, the nh1,nh2,nh3 are using the UDP Destination port that is assigned for IPv4 payload, MPLS Payload and IPv6 payload respectively (MPLS UDP is defined in RFC7510). 

If we come to the last 2 nexthops, nh4 and nh5, they exactly the same as nh1, but they have either a different DSCP value or a different TTL value, or both. 

Let's see the problems now - 

1. Since the nexthops are all udp-v4, how do we define the nexthop group? We can't mix nh1, nh2 and nh3 in the same nexthop group because the intent is do have different payloads for the 3 encaps as defined by the UDP port. How do we restrict this? Even if vendors restrict it at their end, the model definition leaves too much open and may result in a lot of errors. Careful planning will need to be done by end users to ensure the right NH is used in the NHG and then the right prefix points to the NHG i.e. IPv4 prefix uses an NHG that contains NH1 while an MPLS route uses an NHG2 that uses NH2. 
2. Coming to nh4 and nh5 - the parameters are mostly identical except for different DSCP or TTL. The challenge I mentioned in point 1 is still applicable - do we create NHG with different TTL/DSCP? How would this translate in the network? Further even if we support this, we would have no control over which path is selected as that is a final load balancing decision. And this will also impact the scale of the device as we have to create 3 tunnels with the same parameters. 
3. Generally an explicit config at the encap - like a DSCP or TTL should take precedence over any other actions - so if we configure the TTL here, how would Policy actions like the set-ip-ttl references function? Similarly if we wanted to use a QoS policy to set the tunnel DSCP to a new value, what should take precedence? The QoS policy or the value that we intentionally programmed into the tunnel header?

2025-03-06 23:21 UTC, akvasu commented
Another general comment about the encap-header since we are inheriting it from the AFT state - is the Source Port required to be a part of this? In general the GUE draft, VxLAN RFC, MPLSoUDP RFC and GENEVE RFC all hint at deriving the UDP Source port as a function of the packet load balance key. The usecase could be to restrict the number of bits - like maybe having the upper 2 bits of the SRC Port fixed, or maybe the upper 8bits just to reduce the entropy. This would again mostly have to be a system parameter and not a per tunnel as it would be significant challenge to implement a per tunnel Source port masking.

2025-03-11 21:44 UTC, dplore commented on release/models/network-instance/openconfig-network-instance-static.yang
> +            uses oc-aft:aft-common-entry-nexthop-encap-udp-state;
Thanks for catching this, we can tighten this by using the address family specific types `oc-inet:ipv4-address` and `oc-inet:ipv6-address`

2025-03-12 16:55 UTC, dplore commented on release/models/network-instance/openconfig-network-instance-static.yang
> +        }
```suggestion
        container state {
          config false;
          description
            "State parameters relating to encapsulation headers.";

          uses oc-aft:aft-common-nexthop-encap-headers-state;
        }
```

2025-03-12 17:02 UTC, dplore commented on release/models/network-instance/openconfig-network-instance-static.yang
> +            uses oc-aft:aft-common-entry-nexthop-encap-udp-state;
@danameme I suggest making this type change in a separate PR

2025-03-14 18:03 UTC, danameme commented on release/models/local-routing/openconfig-local-routing.yang
> +            next-hop-group.";
I've updated description in latest commit.

2025-03-14 18:03 UTC, danameme commented on release/models/network-instance/openconfig-network-instance-static.yang
> +
Done

2025-03-14 18:04 UTC, danameme commented on release/models/network-instance/openconfig-network-instance-static.yang
> +        }
Updated state container with "config false" in latest commit.

2025-03-14 18:04 UTC, danameme commented on release/models/network-instance/openconfig-network-instance-static.yang
> +            uses oc-aft:aft-common-entry-nexthop-encap-udp-state;
Done. It's in https://github.com/openconfig/public/pull/1265

2025-03-14 21:11 UTC, dplore commented
/gbrun

2025-03-14 22:02 UTC, dplore requested changes

2025-03-14 22:02 UTC, dplore commented on release/models/local-routing/openconfig-local-routing.yang
> +      "Enclosing container for next-hop-group.";
```suggestion
      "Grouping of configuration parameters for a static route's reference 
      to a next-hop-group.";
```

2025-03-15 23:55 UTC, danameme commented on release/models/network-instance/openconfig-network-instance.yang
> +      "Add static GUE encapsulation.";
Updated it.

2025-03-16 00:17 UTC, danameme commented
> hi, i have some doubts can you please help clarify
> 
> QUESTION 1:::::: if we give something like this: set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 config index 1 set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 encap-headers encap-header 1 udp-v4 config dst-ip 1.1.1.1 set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 2 config index 2 set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 2 encap-headers encap-header 2 config index 2 set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 2 encap-headers encap-header 2 udp-v4 config dst-ip 2.2.2.2
> 
> set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP_GROUP nhg1 static-next-hop-groups static-next-hop-group snhg1 next-hops next-hop 2 config index 2
> 
> set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol STATIC DEFAULT static-routes static next-hop-group config name snhg1
> 
> > > > then what is the point of defining index 1 and 2 in protocol NEXT_HOP nh1, if we explicitely have to mention the index in protocol NEXT_HOP_GROUP nhg1 ?
> 
> QUESTION 2::::: if we have a situation like this: set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh2 next-hops next-hop 1 config index 1 set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh2 next-hops next-hop 1 encap-headers encap-header 1 udp-v4 config dst-ip 2.2.2.2
> 
> set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 config index 1 set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 encap-headers encap-header 1 udp-v4 config dst-ip 1.1.1.1
> 
> here for both NEXT_HOP nh2 and NEXT_HOP nh1, we have index 1 defined. how will we deal with this ? are we mentioning somewhere that multiple instances for protocol NEXT_HOP is not allowed ?
> 
> thanks shashank

So both questions are based on the old proposal which NEXT_HOP_GROUP and NEXT_HOP as protocols. This is no longer the proposal.  Can you take a look at the latest proposal in the PR description and let me know if the questions still apply.

In current proposal, each static next-hop is referenced by an index and each static next-hop-group is referenced by a name.

Thanks.

2025-03-16 01:16 UTC, danameme commented
> Can we import the "State" containers into config as done in this PR? When we were working on an alternate proposal in the past within Cisco, we wanted to re-use the AFT definitions, but we didn't as they were only state. Reading back from state doesn't always translate well, as state might be a combination of different hardware objects based on how the ASIC's implement a feature.
> 
> Coming to the content of the PR, I've been discussing the implementation of this model within Cisco and we came up with some concerns, that I'll try to explain here.
> 
> Lets start with defining some Nexthops like this -
> 
> ```
> set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 encap-headers encap-header 1 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6080 dscp af43 ip-ttl 250 
> 
> set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh2 next-hops next-hop 2 encap-headers encap-header 2 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6635 dscp af43 ip-ttl 250 
> 
> set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh3 next-hops next-hop 3 encap-headers encap-header 3 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6615 dscp af43 ip-ttl 250 
> 
> **set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh4 next-hops next-hop 4 encap-headers encap-header 4 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6080 dscp af45 ip-ttl 250** 
> 
> **set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh5 next-hops next-hop 5 encap-headers encap-header 5 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6080 dscp af43 ip-ttl 64** 
> ```
> 
> We have defined 5 nexthops, and they all have the same SRC and DST IP, and all are the same tunnel type udp-v4. Going by our past work, the nh1,nh2,nh3 are using the UDP Destination port that is assigned for IPv4 payload, MPLS Payload and IPv6 payload respectively (MPLS UDP is defined in RFC7510).
> 
> If we come to the last 2 nexthops, nh4 and nh5, they exactly the same as nh1, but they have either a different DSCP value or a different TTL value, or both.
> 
> Let's see the problems now -
> 
> 1. Since the nexthops are all udp-v4, how do we define the nexthop group? We can't mix nh1, nh2 and nh3 in the same nexthop group because the intent is do have different payloads for the 3 encaps as defined by the UDP port. How do we restrict this? Even if vendors restrict it at their end, the model definition leaves too much open and may result in a lot of errors. Careful planning will need to be done by end users to ensure the right NH is used in the NHG and then the right prefix points to the NHG i.e. IPv4 prefix uses an NHG that contains NH1 while an MPLS route uses an NHG2 that uses NH2.
> 2. Coming to nh4 and nh5 - the parameters are mostly identical except for different DSCP or TTL. The challenge I mentioned in point 1 is still applicable - do we create NHG with different TTL/DSCP? How would this translate in the network? Further even if we support this, we would have no control over which path is selected as that is a final load balancing decision. And this will also impact the scale of the device as we have to create 3 tunnels with the same parameters. Consider as a simple case of creating the same tunnel with IPv4 and IPv6 UDP port and say 8 DSCP values. Each tunnel has to be created in hardware 16 times, and that is with the assumption that the ASIC can support duplicate entries involving DSCP and UDP per entry.
> 3. Generally an explicit config at the encap - like a DSCP or TTL should take precedence over any other actions - so if we configure the TTL here, how would Policy actions like the set-ip-ttl references function? Similarly if we wanted to use a QoS policy to set the tunnel DSCP to a new value, what should take precedence? The QoS policy or the value that we intentionally programmed into the tunnel header?
> 
> Can we make the TTL, DSCP config per nexthop optional? I am sure it is optional, just wanted to reconfirm. We could also make a restriction that only 1 DSCP is allowed per NH entry, and similarly only 1 TTL is allowed. This will address the scale concern and also provide a way to modify the entry - we can use the index, and update the parameters, so it gets modified and we don't need to create a new NHG and so on. (Provided the ASIC handles modifications - Cisco ASIC and software can handle update for parameters like DSCP and TTL)

`Can we import the "State" containers into config as done in this PR?` It's the grouping (not containers) that are being used. The grouping contains only leafs that are being re-used.

Quick note: Please see the latest revision of this PR in the description (Tree view). The NH and NHG are no longer configured under protocols/protocol tree.

1. `Since the nexthops are all udp-v4, how do we define the nexthop group? We can't mix nh1, nh2 and nh3 in the same nexthop group` Correct, each next hop has to be defined in a separate nexthop group since the static route references a nexthop group.
2. `do we create NHG with different TTL/DSCP?` Yes, this will be the case. The implementation can translate the config into the way it is supported in hardware especially with regards to repeated fields/scaling concern.
3. `Generally an explicit config at the encap - like a DSCP or TTL should take precedence over any other actions` Yes, this should be the case, not QoS policy.

For the last parts:

a) `Can we make the TTL, DSCP config per nexthop optional? I am sure it is optional, just wanted to reconfirm.` If by optional you mean not configuring these, yes, as you already pointed out. But in the context of above, if you do not configure these for nh1, how will the user's TTL and DSCP values be specified? If you mean considering the user's configured OC value for nh1 as "optional" and having some implementation detail that that does need extra NHG to be created in hardware for nh4 and nh5, that is fine since it'll be an implementation detail. Let me know if my understanding is correct.
b) `We could also make a restriction that only 1 DSCP is allowed per NH entry, and similarly only 1 TTL is allowed.` This will be in the context of having multiple encap headers stacked in a single NH entry, is that correct? If so, I think this is fine. In most cases only one encap header will be in a NH entry.

2025-03-16 01:20 UTC, danameme commented
> Another general comment about the encap-header since we are inheriting it from the AFT state - is the Source Port required to be a part of this? In general the GUE draft, VxLAN RFC, MPLSoUDP RFC and GENEVE RFC all hint at deriving the UDP Source port as a function of the packet load balance key. The usecase could be to restrict the number of bits - like maybe having the upper 2 bits of the SRC Port fixed, or maybe the upper 8bits just to reduce the entropy. This would again mostly have to be a system parameter and not a per tunnel as it would be significant challenge to implement a per tunnel Source port masking.

`Another general comment about the encap-header since we are inheriting it from the AFT state - is the Source Port required to be a part of this?` Not required, but as you noted,  it's coming from the grouping imported from AFT and does not need to be configured by user (configuration of this field is optional).

2025-03-17 01:20 UTC, akvasu commented
> > Another general comment about the encap-header since we are inheriting it from the AFT state - is the Source Port required to be a part of this? In general the GUE draft, VxLAN RFC, MPLSoUDP RFC and GENEVE RFC all hint at deriving the UDP Source port as a function of the packet load balance key. The usecase could be to restrict the number of bits - like maybe having the upper 2 bits of the SRC Port fixed, or maybe the upper 8bits just to reduce the entropy. This would again mostly have to be a system parameter and not a per tunnel as it would be significant challenge to implement a per tunnel Source port masking.
> 
> `Another general comment about the encap-header since we are inheriting it from the AFT state - is the Source Port required to be a part of this?` Not required, but as you noted, it's coming from the grouping imported from AFT and does not need to be configured by user (configuration of this field is optional).

Hi Dan, What happens is that as vendors we need to implement the model has shown here. So we need to add the source port even if it is not used. This adds confusion as what can be the port value and should be actually added in the datapath. So my point was we should not add fields that are not needed. It should be fine to define an "encap header" and a separate "state" field. For example the encap header may not have a counter attribute, but the state might have this.

2025-03-17 01:32 UTC, akvasu commented
> > Can we import the "State" containers into config as done in this PR? When we were working on an alternate proposal in the past within Cisco, we wanted to re-use the AFT definitions, but we didn't as they were only state. Reading back from state doesn't always translate well, as state might be a combination of different hardware objects based on how the ASIC's implement a feature.
> > Coming to the content of the PR, I've been discussing the implementation of this model within Cisco and we came up with some concerns, that I'll try to explain here.
> > Lets start with defining some Nexthops like this -
> > ```
> > set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh1 next-hops next-hop 1 encap-headers encap-header 1 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6080 dscp af43 ip-ttl 250 
> > 
> > set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh2 next-hops next-hop 2 encap-headers encap-header 2 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6635 dscp af43 ip-ttl 250 
> > 
> > set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh3 next-hops next-hop 3 encap-headers encap-header 3 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6615 dscp af43 ip-ttl 250 
> > 
> > **set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh4 next-hops next-hop 4 encap-headers encap-header 4 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6080 dscp af45 ip-ttl 250** 
> > 
> > **set openconfig-network-instance:network-instances network-instance DEFAULT protocols protocol NEXT_HOP nh5 next-hops next-hop 5 encap-headers encap-header 5 udp-v4 config dst-ip 10.10.10.10 src-ip 20.20.20.20 dst-udp-port 6080 dscp af43 ip-ttl 64** 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We have defined 5 nexthops, and they all have the same SRC and DST IP, and all are the same tunnel type udp-v4. Going by our past work, the nh1,nh2,nh3 are using the UDP Destination port that is assigned for IPv4 payload, MPLS Payload and IPv6 payload respectively (MPLS UDP is defined in RFC7510).
> > If we come to the last 2 nexthops, nh4 and nh5, they exactly the same as nh1, but they have either a different DSCP value or a different TTL value, or both.
> > Let's see the problems now -
> > 
> > 1. Since the nexthops are all udp-v4, how do we define the nexthop group? We can't mix nh1, nh2 and nh3 in the same nexthop group because the intent is do have different payloads for the 3 encaps as defined by the UDP port. How do we restrict this? Even if vendors restrict it at their end, the model definition leaves too much open and may result in a lot of errors. Careful planning will need to be done by end users to ensure the right NH is used in the NHG and then the right prefix points to the NHG i.e. IPv4 prefix uses an NHG that contains NH1 while an MPLS route uses an NHG2 that uses NH2.
> > 2. Coming to nh4 and nh5 - the parameters are mostly identical except for different DSCP or TTL. The challenge I mentioned in point 1 is still applicable - do we create NHG with different TTL/DSCP? How would this translate in the network? Further even if we support this, we would have no control over which path is selected as that is a final load balancing decision. And this will also impact the scale of the device as we have to create 3 tunnels with the same parameters. Consider as a simple case of creating the same tunnel with IPv4 and IPv6 UDP port and say 8 DSCP values. Each tunnel has to be created in hardware 16 times, and that is with the assumption that the ASIC can support duplicate entries involving DSCP and UDP per entry.
> > 3. Generally an explicit config at the encap - like a DSCP or TTL should take precedence over any other actions - so if we configure the TTL here, how would Policy actions like the set-ip-ttl references function? Similarly if we wanted to use a QoS policy to set the tunnel DSCP to a new value, what should take precedence? The QoS policy or the value that we intentionally programmed into the tunnel header?
> > 
> > Can we make the TTL, DSCP config per nexthop optional? I am sure it is optional, just wanted to reconfirm. We could also make a restriction that only 1 DSCP is allowed per NH entry, and similarly only 1 TTL is allowed. This will address the scale concern and also provide a way to modify the entry - we can use the index, and update the parameters, so it gets modified and we don't need to create a new NHG and so on. (Provided the ASIC handles modifications - Cisco ASIC and software can handle update for parameters like DSCP and TTL)
> 
> `Can we import the "State" containers into config as done in this PR?` It's the grouping (not containers) that are being used. The grouping contains only leafs that are being re-used.
> 
> Quick note: Please see the latest revision of this PR in the description (Tree view). The NH and NHG are no longer configured under protocols/protocol tree.
> 
> 1. `Since the nexthops are all udp-v4, how do we define the nexthop group? We can't mix nh1, nh2 and nh3 in the same nexthop group` Correct, each next hop has to be defined in a separate nexthop group since the static route references a nexthop group.
> 2. `do we create NHG with different TTL/DSCP?` Yes, this will be the case. The implementation can translate the config into the way it is supported in hardware especially with regards to repeated fields/scaling concern.
> 3. `Generally an explicit config at the encap - like a DSCP or TTL should take precedence over any other actions` Yes, this should be the case, not QoS policy.
> 
> For the last parts:
> 
> a) `Can we make the TTL, DSCP config per nexthop optional? I am sure it is optional, just wanted to reconfirm.` If by optional you mean not configuring these, yes, as you already pointed out. But in the context of above, if you do not configure these for nh1, how will the user's TTL and DSCP values be specified? If you mean considering the user's configured OC value for nh1 as "optional" and having some implementation detail that that does need extra NHG to be created in hardware for nh4 and nh5, that is fine since it'll be an implementation detail. Let me know if my understanding is correct. b) `We could also make a restriction that only 1 DSCP is allowed per NH entry, and similarly only 1 TTL is allowed.` This will be in the context of having multiple encap headers stacked in a single NH entry, is that correct? If so, I think this is fine. In most cases only one encap header will be in a NH entry.


Thanks for the updates. In the current form, I still see the "encap-headers" with an "index" Do we expect to have a "Next-hop" and a "set of encap headers" or will it be [nexthop <index> encap header  <index> [encap fields]] ? If we have an array of encap headers per nexthop, my question is still valid - how do we define what to use in the NHG? I noticed we only use next-hop-index, so this still leaves it open. I think if the nexthop has the unique index, we don't need another one at the encap-header level. The encap-header can just have the type and attributes. I think Shashank's comment is along similar lines. 

Regarding the questions and your responses - I am updating mine here - 

1. It makes sense to create different NHG's but this will also consume the system scale. In future we might want to ensure the NHG is "viable" before using it in the route (gRIBI has such a guarantee) - so this model can increase scale and having to duplicate entries just for TTL/DSCP is not efficient. 
2. If the TTL and DSCP are not configured, then the system behavior will be used i.e. for TTL we will inherit it from the incoming packet ("uniform" mode) and for "DSCP" we could use a QoS policy to set it (if we don't want "uniform" mode). It mi [...]

2025-03-17 22:03 UTC, dplore commented on release/models/local-routing/openconfig-local-routing.yang
>          container next-hops {
on further discussion, we decided not to use the `status deprecate` directive, in order to avoid confusion over whether this field needs to be supported in OC.  Instead, the description can just be modified the say that this container may be removed in the future and be obsoleted by the `/network-instances/network-instance/static/next-hop-groups`.

2025-03-17 22:12 UTC, dplore commented
> Thanks for the updates. In the current form, I still see the "encap-headers" with an "index" Do we expect to have a "Next-hop" and a "set of encap headers" or will it be [nexthop encap header [encap fields]] ? If we have an array of encap headers per nexthop, my question is still valid - how do we define what to use in the NHG? I noticed we only use next-hop-index, so this still leaves it open. I think if the nexthop has the unique index, we don't need another one at the encap-header level. The encap-header can just have the type and attributes. I think Shashank's comment is along similar lines.
> 


We have two use cases for encapsulation using next-hop-groups at the moment: 
a. one encap-header, udpv4
b. two encap-headers,  mpls and gre


> Regarding the questions and your responses - I am updating mine here -
> 
> 1. It makes sense to create different NHG's but this will also consume the system scale. In future we might want to ensure the NHG is "viable" before using it in the route (gRIBI has such a guarantee) - so this model can increase scale and having to duplicate entries just for TTL/DSCP is not efficient.


> 2. If the TTL and DSCP are not configured, then the system behavior will be used i.e. for TTL we will inherit it from the incoming packet ("uniform" mode) and for "DSCP" we could use a QoS policy to set it (if we don't want "uniform" mode). It might also be possible to define a system wide default behavior for TTL - "uniform vs pipe" and in "pipe" the outer gets set to the max or a common global value. We should not ignore the implementation detail as that increases the complexity and impacts the feature delivery. And different vendors might make different choices which may impact the requirement.

We have scenarios where we want 
- the encap-header (outermost)  TTL to be inherited from the inner packet 
- the encap-header (outermost) TTL set to a configured value

> 3. If we can enforce a single encap header then a lot of things become simple - so can we update the model this way? I

As noted above, we have use cases for single and for multiple headers today.

2025-03-18 17:38 UTC, danameme commented
> > Thanks for the updates. In the current form, I still see the "encap-headers" with an "index" Do we expect to have a "Next-hop" and a "set of encap headers" or will it be [nexthop encap header [encap fields]] ? If we have an array of encap headers per nexthop, my question is still valid - how do we define what to use in the NHG? I noticed we only use next-hop-index, so this still leaves it open. I think if the nexthop has the unique index, we don't need another one at the encap-header level. The encap-header can just have the type and attributes. I think Shashank's comment is along similar lines.
> 
> We have two use cases for encapsulation using next-hop-groups at the moment: a. one encap-header, udpv4 b. two encap-headers, mpls and gre
> 
> > Regarding the questions and your responses - I am updating mine here -
> > 
> > 1. It makes sense to create different NHG's but this will also consume the system scale. In future we might want to ensure the NHG is "viable" before using it in the route (gRIBI has such a guarantee) - so this model can increase scale and having to duplicate entries just for TTL/DSCP is not efficient.
> 
> > 2. If the TTL and DSCP are not configured, then the system behavior will be used i.e. for TTL we will inherit it from the incoming packet ("uniform" mode) and for "DSCP" we could use a QoS policy to set it (if we don't want "uniform" mode). It might also be possible to define a system wide default behavior for TTL - "uniform vs pipe" and in "pipe" the outer gets set to the max or a common global value. We should not ignore the implementation detail as that increases the complexity and impacts the feature delivery. And different vendors might make different choices which may impact the requirement.
> 
> We have scenarios where we want
> 
> * the encap-header (outermost)  TTL to be inherited from the inner packet
> * the encap-header (outermost) TTL set to a configured value
> 
> > 3. If we can enforce a single encap header then a lot of things become simple - so can we update the model this way? I
> 
> As noted above, we have use cases for single and for multiple headers today.

Thanks Darren. I clarified the use of the "index" field in the "encap-headers" as you indicated, offline with Anup and team. This is fine.

And we discussed, we'll have a follow PR to about using template for repeated fields to reduce the scale concerns mentioned.

2025-03-19 16:52 UTC, dplore reviewed
suggested updates for the nodes which "in the future will be deprecated"

2025-03-19 16:52 UTC, dplore commented on release/models/local-routing/openconfig-local-routing.yang
> +            route prefix then the next-hops container should not be used.";
```suggestion
            next-hop-group. In the future, this container will replace the container
            /network-instances/network-instance/protocols/protocol/static-routes/static/next-hops.
            If a statically configured next-hop-group is used for a static route
            prefix then the 'static-routes/static/next-hops' container must not
            be used.";
```

2025-03-19 16:52 UTC, dplore commented on release/models/local-routing/openconfig-local-routing.yang
> +            not be used.";
```suggestion
          description
            "Configuration and state parameters relating
            to the next-hops that are to be utilised for the static
            route being specified.
            In the future, this container will be deprecated in favor of the
            /network-instances/network-instance/static/next-hop-groups
            container. If a statically configured next-hop-group is used
            for a static route prefix then the 'static-routes/static/next-hops'
            container must not be used.";
```

2025-03-19 16:52 UTC, dplore commented on release/models/local-routing/openconfig-local-routing.yang
>                route being specified.";
```suggestion
              "A list of next-hops to be utilised for the static
              route being specified.  In the future, this list will be
              deprecated in favor of
              /network-instances/network-instance/static/next-hop-groups.";
```

2025-03-19 18:32 UTC, dplore approved these changes

2025-03-19 19:32 UTC, dplore approved these changes
LGTM.   Thanks for all the collaboration from the community on this. A follow up PR will extend this model to utilize templates to allow for a more efficient configuration when there are many (thousands) of NHG,NH.

2025-03-19 19:33 UTC, merged