adds extended next-hop encoding config/state for BGP
openconfig/public pull request #513
Opened 2021-10-25 22:42 UTC by sulrich

adds support for RFC5549 extended next-hop encoding
 * (M) bgp/openconfig-bgp-common-multiprotocol.yang
  - slightly restructures the mp-ipv4-ipv6-unicast-common groupings to allow for
    the addition of the extended-next-hop-encoding leaf in the top-level IPv4
    unicast config/state containers.

2021-11-09 22:19 UTC, wenovus commented
goyang/ygot's failure is due to an outdated CI image. When you retrigger the CI now it should bypass the current failure.

2021-11-15 13:26 UTC, robshakir reviewed
For reviewing ease, this PR adds the following paths:

```
▶ diff /tmp/master /tmp/513
1629a1630
>        [rw] /network-instances/network-instance/protocols/protocol/bgp/global/afi-safis/afi-safi/ipv4-unicast/config/extended-next-hop-encoding
1631a1633
>        [ro] /network-instances/network-instance/protocols/protocol/bgp/global/afi-safis/afi-safi/ipv4-unicast/state/extended-next-hop-encoding
1978a1981
>        [rw] /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/ipv4-unicast/config/extended-next-hop-encoding
1980a1984
>        [ro] /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/ipv4-unicast/state/extended-next-hop-encoding
2317a2322
>        [rw] /network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/ipv4-unicast/config/extended-next-hop-encoding
2319a2325
>        [ro] /network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/ipv4-unicast/state/extended-next-hop-encoding
```

@sulrich -- we generally ask that PRs describe the support across other major OSes. Something like:

 * Cisco IOS XR does not support this as a flag, and seems to enable RFC5549 by default.
 * JUNOS supports this with `set protocols bgp family inet unicast extended-nexthop`. ([docs](https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/topic-map/multiprotocol-bgp.html#id-understanding-redistribution-of-ipv4-routes-with-ipv6-next-hop-into-bgp))
 * EOS supports this with `bgp next-hop address-family ipv6` (no public docs :cry:)
 * SROS supports this with `advertise-ipv6-nexthops` [(docs](https://documentation.nokia.com/cgi-bin/dbaccessfilename.cgi/3HE15831AAADTQZZA01_V1_7450%20ESS%207750%20SR%207950%20XRS%20and%20VSR%20Unicast%20Routing%20Protocols%20Guide%2020.10.R1.pdf))

Given that XR is the only platform that doesn't feature flag this, I think this qualifies as being something that we should include in the models.

I'll take this change upstream - the above is an FYI to speed up future contributions review process :-)

2021-11-15 13:42 UTC, robshakir commented
Actually, @sulrich -- please can you ensure that all submodules of `openconfig-bgp` have the same version? It looks like you just updated a subset.

@wenovus / @dplore -- can you maybe put your heads together and figure out a CI check for this please! Thank you!

2021-12-14 18:29 UTC, dplore commented
@robshakir would you like to approve and merge this one as is?

2022-04-22 22:23 UTC, robshakir commented
@sulrich Please fix the trailing whitespace.

2022-04-27 23:09 UTC, dplore requested changes
LGTM, but needs to be rebased/merged with master

2022-05-02 16:34 UTC, dplore commented
Hi @sulrich you need to rebase/merge with master (which will resolve the linter issues from files that you didn't even touch) and this will be ready to go

2022-05-02 18:03 UTC, sulrich commented
sorry about that. fixed.

2022-05-02 18:10 UTC, dplore commented
Thanks @sulrich , queued for review at openconfig operators meeting on May 3rd

2022-05-18 01:01 UTC, dplore commented
@sulrich there was a change that bumped the version in bgp that went in ahead of your PR.  If you would like to rebase again  and bump the version, we can get this merged.  Thanks for your understanding!

2022-05-21 15:34 UTC, sulrich commented
@dplore bumped versions per above

2022-05-23 17:23 UTC, merged

2022-05-23 17:23 UTC, dplore commented
Thanks for the contribution @sulrich !