Add atomic annotations to containers in openconfig-aft.
openconfig/public pull request #517
Opened 2021-10-29 16:16 UTC by drautio

On branch aft-atomic-508
 Changes to be committed:
	modified:   openconfig-aft-common.yang
	modified:   openconfig-aft-ethernet.yang
	modified:   openconfig-aft-ipv4.yang
	modified:   openconfig-aft-ipv6.yang
	modified:   openconfig-aft-mpls.yang
	modified:   openconfig-aft-pf.yang

Add the atomic attribute to the above aft yang containers.

2021-11-09 22:18 UTC, wenovus commented
goyang/ygot's failure is due to an outdated CI image. When you retrigger the CI now it should bypass the current failure.

2021-11-15 13:01 UTC, robshakir requested changes
Thanks for this change. I think we need to consider where this is added in the file for readability -- suggested some comments throughout.

2021-12-14 18:31 UTC, dplore commented
Checking in with you @drautio.  Would you like to move forward to address the comments?

2022-01-26 18:53 UTC, drautio commented
I made the requested changes.  Thanks for the review!

- Dan

2023-02-15 16:16 UTC, robshakir commented on release/models/aft/openconfig-aft-common.yang
> +      "Add atomic attribute to the next-hops container.";
This revision description should be common across all the files, rather than one per file.

2023-02-15 16:17 UTC, robshakir commented on release/models/aft/openconfig-aft-common.yang
> +	oc-ext:telemetry-atomic;
The indentation here should match that of `key` above.

2023-02-15 18:15 UTC, michaelore commented
I'll update this PR if I can get that to work, or otherwise make a new PR.

We'll take care of this, Dan. :)

2023-04-19 15:58 UTC, dplore commented
Closed in favor of #860

2023-04-19 15:58 UTC, closed without merging