Update remainder of regex pattern statements for XSD conformance
openconfig/public pull request #534
Opened 2021-12-06 18:07 UTC by earies

* (M) release/models/bgp/openconfig-bgp-policy.yang
* (M) release/models/openflow/openconfig-openflow-types.yang
* (M) release/models/policy/openconfig-routing-policy.yang
* (M) release/models/vlan/openconfig-vlan-types.yang
* (M) release/models/wifi/openconfig-ap-manager.yang
  - Remove anchors in pattern statements to make them W3C compliant
  - Remove regex-posix extension from these updated modules

This PR covers a few artifacts remaining through the models where YANG pattern
statements were not updated to reflect the XSD regex variants.  In addition to
the regex updates are removal of the oc-ext:regexp-posix flavor extension
statements.

NOTE: This PR only covers the modules where pattern statements were still
broken.  An additional PR will cover removal of oc-ext:regexp-posix across all
modules.

2021-12-14 23:37 UTC, dplore commented
LGTM
oc-ext:regexp-posix is no longer used, these modules were missed from earlier cleanup
All other changes are removing ^ %  from the regex strings

2022-03-22 23:02 UTC, wenovus reviewed
So the reason why these were left unconverted is because we wanted to add unit testing for them prior to changing them. e.g. https://github.com/openconfig/models/pull/920/files

If these don't have unit tests, could we open a tracking issue to add them?

2022-03-22 23:27 UTC, earies commented
> So the reason why these were left unconverted is because we wanted to add unit testing for them prior to changing them. e.g. https://github.com/openconfig/models/pull/920/files
> 
> If these don't have unit tests, could we open a tracking issue to add them?

Thx @wenovus but you are referencing a private repo that many folks don't have access to so cannot see what this entails

2022-03-22 23:29 UTC, wenovus commented
> > So the reason why these were left unconverted is because we wanted to add unit testing for them prior to changing them. e.g. https://github.com/openconfig/models/pull/920/files
> > If these don't have unit tests, could we open a tracking issue to add them?
> 
> Thx @wenovus but you are referencing a private repo that many folks don't have access to so cannot see what this entails

Ah apologies, here is an example from the public repo: https://github.com/openconfig/public/pull/460/files

2022-03-22 23:31 UTC, wenovus commented
The PR is closed, but was merged upstream.

The reason why we were waiting for unit tests is that there are some differences between XSD regex and POSIX regex aside from the anchors. Considering I never noticed any in practice during the conversion I think there is a good likelihood this will work, I just want to make sure if we're doing this to unblock some folks that we're tracking that the tests will be added at some point.

2022-05-24 22:41 UTC, dplore commented
@earies you could add a yang regex validator here:  https://github.com/openconfig/public/tree/master/regexp-tests 

Wen confirmed with me that you can make that validator change part of this same PR and the CI checks will execute it as part of your PR together.   BTW, placing a comment with the following text will force the CI to run again:

```
/gcbrun
```

2022-05-25 01:41 UTC, earies commented
> @earies you could add a yang regex validator here: https://github.com/openconfig/public/tree/master/regexp-tests
> 
> Wen confirmed with me that you can make that validator change part of this same PR and the CI checks will execute it as part of your PR together. BTW, placing a comment with the following text will force the CI to run again:
> 
> ```
> /gcbrun
> ```

Will update accordingly but note that any inline pattern statements (e.g. non-reusable types) cannot be covered here without complete duplication of the string pattern in the test which is a de-synchronized exercise I don't think we want to do in this fashion (`masklength-range` is one such example here)

2022-05-25 01:59 UTC, earies commented
@dplore @wenovus @aashaikh - note there are a few issues w/ regexp tests

* 2 nodes in this patch set have inline pattern statements.  These types of tests cannot accommodate so there will be no coverage for such (There is lacking coverage already in other modules for this) - From this patch set it is `masklength-range` and `country-code`
* For typedefs in non `-types` modules means an import of that module which cascades dependencies in this case from openflow -> interfaces -> ietf-interfaces and ietf-interfaces is not an OpenConfig module thus fails the regexp tests

It seems the regexp framework would need some additional work and don't see that as blocking the fixup of these remaining invalid regexes.  The types module tests included in here can remain but the policy test module would need to be removed

2022-05-25 03:31 UTC, wenovus requested changes

2022-05-25 03:31 UTC, wenovus commented on release/models/vlan/openconfig-vlan-types.yang
> -  oc-ext:regexp-posix;
Since this is a module-level modifier could you also help convert `qinq-id` and `qinq-id-range` and add tests for them?

2022-05-25 03:33 UTC, wenovus commented
> @dplore @wenovus @aashaikh - note there are a few issues w/ regexp tests
> 
> * 2 nodes in this patch set have inline pattern statements.  These types of tests cannot accommodate so there will be no coverage for such (There is lacking coverage already in other modules for this) - From this patch set it is `masklength-range` and `country-code`
> * For typedefs in non `-types` modules means an import of that module which cascades dependencies in this case from openflow -> interfaces -> ietf-interfaces and ietf-interfaces is not an OpenConfig module thus fails the regexp tests
> 
> It seems the regexp framework would need some additional work and don't see that as blocking the fixup of these remaining invalid regexes. The types module tests included in here can remain but the policy test module would need to be removed

Thanks for the work here, SGTM let's not block the tests on these two types of regexes, feel free to comment out the non-working tests and create an issue assigning to me and I will look at enabling them.

2022-05-25 13:23 UTC, earies commented
> * 2 nodes in this patch set have inline pattern statements.  These types of tests cannot accommodate so there will be no coverage for such (There is lacking coverage already in other modules for this) - From this patch set it is `masklength-range` and `country-code`
> 
> * For typedefs in non `-types` modules means an import of that module which cascades dependencies in this case from openflow -> interfaces -> ietf-interfaces and ietf-interfaces is not an OpenConfig module thus fails the regexp tests

PR updated and passing tests w/ coverage for the `-types` module changes

Issue https://github.com/openconfig/public/issues/648 opened for tracking regexp test enhancements.  @dplore @wenovus - direct assignment of issues/PRs is restricted so you may want to consider opening this up for easier tagging

2022-05-25 16:17 UTC, wenovus approved these changes
LGTM, I'll leave to Darren to determine whether the test cases have sufficient coverage.

2022-05-25 17:16 UTC, dplore approved these changes
LGTM, thank you

2022-05-25 17:17 UTC, merged