Add support of the packet length and several protocols filter
openconfig/public pull request #609
Opened 2022-03-29 12:36 UTC by sbarguil

Add support of the packet length and several protocols filter. 
Add ICMP field in IPv4 and IPv6 packets

2022-03-29 12:37 UTC, sbarguil commented
Cames from https://github.com/openconfig/models/pull/988

2022-04-22 22:04 UTC, robshakir requested changes
Per the usual requests -- can we add some references to >= 2 implementations that support this behaviour? I believe that they exist. I'd just like to make sure that we have this clearly documented for each PR.

2022-04-22 22:04 UTC, robshakir commented on release/models/acl/openconfig-packet-match.yang
> +      type uint8;
Should we have this as an `enumeration`? We have an internal model that has the definitions of the ICMPv4 and ICMPv6 types that I can propose as an addition if this makes sense.

2022-11-30 12:26 UTC, sourcequench commented on release/models/acl/openconfig-packet-match.yang
> +      "Add ICPM Fields for filtering.";
s/ICPM/ICMP

2023-01-27 05:03 UTC, robshakir commented on release/models/acl/openconfig-packet-match.yang
> +    leaf icmp-type {
Addressed in the forked PR.

2024-07-18 02:46 UTC, closed without merging