Switchover ready
openconfig/public pull request #667
Opened 2022-07-11 22:18 UTC by rolandphung

* (M) release/models/platform/openconfig-platform.yang
  - Add boolean switchover-ready leaf

Add an indication for when redundant components are ready to failover.

Relevant pyang output:
```
module: openconfig-platform
  +--rw components
     +--rw component* [name]
        +--ro state
           +--ro switchover-ready?   boolean
```

References:
* Arista `show redundancy status`
  * https://www.arista.com/en/um-eos/eos-supervisor-redundancy
* Juniper `show system switchover`
  * https://www.juniper.net/documentation/us/en/software/junos/high-availability/topics/ref/command/show-system-switchover.html
* Cisco `show redundancy states`
  * https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9400/software/release/16-9/command_reference/b_169_9400_cr/high_availability_commands.html#reference_t1d_ppp_dgb

2022-07-12 04:30 UTC, dplore requested changes
Small nit on the description text

2022-07-12 04:30 UTC, dplore commented on release/models/platform/openconfig-platform.yang
> +        of that indicates if the secondary component is ready to
```suggestion
       that indicates if the secondary component is ready to
```

2022-07-13 00:38 UTC, dplore approved these changes

2022-07-13 00:39 UTC, dplore commented
@earies @rgwilton for any comments

2022-07-18 16:08 UTC, aredmon8551 commented
Clarification - should this RPC be available on both supervisors/routing-engines, or only the backup/redundant one?

2022-07-18 16:47 UTC, dplore commented
IMO, primary and secondary should both support the leaf.  

It's also good to get a consistent answer whether querying the primary or secondary CONTROLLER_CARD (to use OC language). It seems the primary should be 'ready' if the secondary is also 'ready'.    Does that make sense?  We can add description to clarify this.

2022-07-18 16:52 UTC, rolandphung commented
Agreed. I think it makes more sense in a scenario where there are more than 2 redundant components. The primary stating that it is "ready" is signaling that at least one component is ready to failover.

Let me see how to word this into the description.

2022-07-20 05:21 UTC, dplore requested changes
Suggested clarification

2022-07-20 05:21 UTC, dplore commented on release/models/platform/openconfig-platform.yang
> +        supervisors in a device should both report the same value.";
```suggestion
        "For components that have redundant roles, this reports a value
        that indicates if the component is ready to support failover.

        The components with a redundant-role  should reflect the overall 
        system's switchover status.  For example, two supervisors in a 
        device, one as primary and the other as secondary, should both 
        report the same value.";
```

2022-07-21 02:16 UTC, dplore approved these changes

2022-07-21 02:18 UTC, dplore commented
Holding until July 22 (2 weeks after PR submitted) for any additional community feedback

2022-07-22 15:40 UTC, robshakir approved these changes

2022-07-25 03:41 UTC, dplore commented
/gcbrun

2022-07-25 04:10 UTC, merged