Add csnp-enable-on-p2p-links leaf to IS-IS global configuration.
openconfig/public pull request #712
Opened 2022-09-21 00:13 UTC by hariramnat

### Original Problem

We need to be able to disable CSNP on a global level. This requires specifying csnp enable/disable for p2p links at global IS-IS configuration. 

### Proposed Solution
 Add a csnp-enable-on-p2p-links leaf of type boolean  to isis-global-config, set to false by default.

2022-09-22 00:00 UTC, dplore commented
Thanks for this contribution.  Please check the [contributions](https://github.com/openconfig/public/blob/master/doc/contributions-guide.md) guide and provide references to at least two implementations.   For an example, see #667

2022-09-22 21:50 UTC, hariramnat commented
Done. Added references

2022-09-24 00:18 UTC, dplore commented
Thanks Hariram.   @earies @rgwilton @rolandphung @hellt for comment.

2022-09-24 01:05 UTC, dplore commented
I have added this to the Sep 27 OpenConfig operators agenda

2022-09-27 20:40 UTC, hariramnat commented
Hey @earies @rgwilton @rolandphung @hellt, 

Is there anything else that you would like me to add to this contribution?

2022-09-27 21:53 UTC, dplore commented
This was reviewed in the Sep 27 OC operators meeting with no comments received.  We can merge this in 2 weeks (Oct 11, 2022) if there are no objections.

2022-10-12 04:50 UTC, dplore requested changes
Hi @hariramnat ,  I see that for the implementations referenced, CSNP is enabled by default.  I think it would be more compatible and still vendor neutral to make enabled default to true.

2022-10-14 20:58 UTC, hariramnat commented
Hey Darren, 

Have made the default to True now. 

Let me know if you have any more changes. 

Thanks

2022-10-19 19:50 UTC, dplore commented
/gcbrun

2022-10-19 19:56 UTC, dplore approved these changes
LGTM!

2022-10-19 19:57 UTC, merged