Support setting priority for every VRRP track interface
openconfig/public pull request #829
Opened 2023-03-10 03:58 UTC by lllyfeng

[Note: Please fill out the following template for your pull request. lines
tagged with "Note" can be removed from the template.]

[Note: Before this PR can be reviewed please agree to the CLA covering this
repo. Please also review the contribution guide -
https://github.com/openconfig/public/blob/master/doc/external-contributions-guide.md]

### Change Scope

* Currently YANG module can only support set one priority for all VRRP tracked interfaces. It's inconvient 
   if one tracked interface wants to have a different priority. So there should be a list for VRRP track interfaces
  with two numbers, interface and priority-decrement.
OLD:
+--rw interface-tracking
       |              +--rw config
       |              |  +--rw track-interface* leafref
       |              |  +--rw priority-decrement? uint8

NEW:
 +--rw interface-tracking
       |              +--rw config
       |              |  +--rw track-interface* [interface]
       |              |     +--rw interface leafref
       |              |     +--rw priority-decrement? uint8
   
* [non-backwards compatible.]
### Platform Implementations

 * H3C: [https://www.h3c.com/en/Support/Resource_Center/HK/Switches/H3C_S7500E/S7500E/Technical_Documents/Configure___Deploy/Configuration_Guides/S7500E_OM(6300_V1.03)/08-System_Volume/200912/658916_294551_0.htm](https://www.h3c.com/en/Support/Resource_Center/HK/Switches/H3C_S7500E/S7500E/Technical_Documents/Configure___Deploy/Configuration_Guides/S7500E_OM(6300_V1.03)/08-System_Volume/200912/658916_294551_0.htm)
 * Junos: [https://www.juniper.net/documentation/us/en/software/junos/high-availability/topics/ref/statement/track-edit-interfaces-vrrp.html](https://www.juniper.net/documentation/us/en/software/junos/high-availability/topics/ref/statement/track-edit-interfaces-vrrp.html)

2023-03-13 01:22 UTC, lllyfeng commented on release/models/interfaces/openconfig-if-ip.yang
>      container interface-tracking {
I have updated it. Thanks.

2023-08-01 16:35 UTC, oscargdd commented
I have reviewed the proposal and I have one big concern. Current model DO support setting the priority for every VRRP track interface. The VRRP track interface configuration is applied PER interface, within the interfaces container.

2023-08-02 20:56 UTC, rolandphung commented
Now that I think about it, we are making a breaking change and it might be worth considering adding a possible second action that would shutdown the VRRP instance instead. Perhaps this could be represented as an enum/identity leaf called `action` and the possible values would be `PRIORITY_DECREMENT` and `DISABLE`/`SHUTDOWN`.

Ref: https://www.arista.com/en/um-eos/eos-varp#xx1153490

2023-08-02 22:34 UTC, dplore requested changes
This was reviewed at the Aug 1, 2023 OC operators meeting.    I have a few small comments that should be addressed.

@oscargdd @s19nal will investigate use cases in their own networks for other options that may be needed.  For our network there are scenarios where track interface is used with a priority decrement.  In the examples I found, we we only tracking one interface.

It does seem legitimate to use a different priority for different interfaces, if for example the interfaces being tracked are of different capacity or importance due to the path or cost of the interfaces being tracked.

2023-08-02 22:34 UTC, dplore commented on release/models/interfaces/openconfig-if-ip.yang
> +      description "the track interface";
```suggestion
      description "The tracked interface.";
```

2023-08-02 22:34 UTC, dplore commented on release/models/interfaces/openconfig-if-ip.yang
> +                  the tracked interface goes down";
Multi line description should be formatted like:

```
description
  "Set the value to subtract from priority when
  the tracked interface goes down.";
```

2023-08-02 22:37 UTC, dplore commented
Note, does this need to be a breaking change?   Since a new container with a different name than the leaf-list is being  introduced, the leaf-list could instead be deprecated and the container added.  This would make this a non-breaking change and expidite it's merging into the OpenConfig model set.

2024-03-05 17:59 UTC, dplore commented
@lllyfeng waiting for your response on this PR.  Thanks

2024-05-14 16:47 UTC, dplore commented
@lllyfeng please address comments if you would like to proceed.  I think the only comment that really should be addressed is the one about deprecation vs. making a breaking change.  (https://github.com/openconfig/public/pull/829#issuecomment-1663060498)

2024-11-25 03:00 UTC, closed without merging